### ISSUE TITLE
Create tool_data_path with other directories

### ISSUE THREAD

**Issue by maikknebel** [galaxyproject/ansible-galaxy#115]
Can the `tool_data_path`, defined in `galaxy_config.galaxy.tool_data_path` be added to the folder creation task?

I try to deploy a blastdb.loc, but the tool_data_path-directory hasn't been created at the time where the galaxy_config_files-array gets processed.

```
galaxy_config_files:
  - src: files/galaxy/blastdb.loc
    dest: "{{ galaxy_mutable_data_dir }}/tool-data/blastdb.loc"
  - src: files/galaxy/blastdb_p.loc
    dest: "{{ galaxy_mutable_data_dir }}/tool-data/blastdb_p.loc"
...
galaxy_config:
  galaxy:
    tool_data_path: {{ galaxy_mutable_data_dir }}/tool-data
```
