### ISSUE TITLE
Use local tool dirs

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/ansible-galaxy#128]
Hi,
I noticed that when you use directories for your local tool instead of just a xml (for example, if you need another python script), it will not update the local_tool_conf.xml:
https://github.com/galaxyproject/ansible-galaxy/blob/a834b46a0c2d13e07470abfb82255232a926e6f8/templates/local_tool_conf.xml.j2#L4-L6
In my case I put in my group_var:
```
galaxy_local_tools:
  - splitbedGraphFromBed
  - ScaleBedGraph

```
And I have:
```
$ tree files/galaxy/tools/
files/galaxy/tools/
├── ScaleBedGraph
│   ├── ScaleBedGraph.sh
│   └── ScaleBedGraph.xml
└── splitbedGraphFromBed
    ├── splitbedGraphFromBed.py
    └── splitbedGraphFromBed.xml

2 directories, 4 files
```
Then I needed to put a `templates/galaxy/config/tool_conf.xml.j2` with all the default tools + at the end:
```
  <section id="LDtools" name="LDtools">
    <tool file="{{ galaxy_local_tools_dir }}/splitbedGraphFromBed/splitbedGraphFromBed/splitbedGraphFromBed.xml" />
    <tool file="{{ galaxy_local_tools_dir }}/ScaleBedGraph/ScaleBedGraph/ScaleBedGraph.xml" />
  </section>
```
Were there a better way?
Something like:
```
{% for tool in galaxy_local_tools %}
{% if not tool.endswith('.xml') %}
    <tool file="{{ galaxy_local_tools_dir }}/{{ tool }}/{{ tool }}/{{ tool }}.xml" />
{% endif %}
{% endfor %}
```
?
Also I found a bit strange there the `tool` directory is put in a directory `tool`...

**Comment by elichad** [comment]
I just ran into this also. It would be useful for the local tool template to loop through the tool directory looking for XML files if you can determine that it's a directory and not an XML file, but I don't know if that's within the scope of possibility with the templates.

I'll also use a custom `tool_conf.xml.j2` template to work around this for now.

**Comment by jarrah42** [comment]
Changing `tasks/static_setup.yml` as follows may fix the directory in directory problem:

```
    - name: Install local tools
      copy:
        src: "{{ galaxy_local_tools_src_dir }}/{{ item }}"
        dest: "{{ galaxy_local_tools_dir }}"
        mode: preserve
      with_items: "{{ galaxy_local_tools | default([]) }}"
      when: galaxy_local_tools is defined
```
