### ISSUE TITLE
Auto update of requirements in virtualenv

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/ansible-galaxy#156]
Dear All,

First of all thanks so much for this role! 

I have used a modified version of this role to install Galaxy in a privilege separation mode. As the virtualenv is owned by a privsep user, galaxy (galaxy user) can not auto update the newly arising requirements in the virtualenv (e.g due to enabling new options in the config) .  
For example the `drmaa` package is not installed by default. The option in the role defaults where the packages to install in the virtualenv seem to be mentioned here - 
```
galaxy_requirements_file: "{{ galaxy_server_dir }}/lib/galaxy/dependencies/pinned-requirements.txt"
```
Should I add required packages (e.g drmaa ) to the `pinned-requirements.txt` in the Galaxy source  ?  Or is there a way that I have missed? Also is there a way to know which packages are not present when a new option is enabled in the configs.  E.g when enabling cluster access in job config, the information that the `drmaa` package is missing and needs to be added. 

Thanks Again and please let me know if something is missing/wrong in this post.
Regards,
Saurabh

**Comment by natefoo** [comment]
`drmaa` is a conditional dependency and is installed if a drmaa-backed runner plugin is enabled in Galaxy's job config. This happens in the role via these tasks in [dependencies.yml](https://github.com/galaxyproject/ansible-galaxy/blob/c15de9f403c0a8a3702aa78d5d1959e9e6c8f6e5/tasks/dependencies.yml):

```yaml
    - name: Collect Galaxy conditional dependency requirement strings
      command: "{{ galaxy_venv_dir }}/bin/python -c \"import galaxy.dependencies; print('\\n'.join(galaxy.dependencies.optional('{{ galaxy_config_file }}')))\""
      environment:
        PYTHONPATH: "{{ galaxy_server_dir }}/lib"
      register: conditional_dependencies
      changed_when: no

    - name: Install Galaxy conditional dependencies
      pip:
        name: "{{ conditional_dependencies.stdout_lines }}"
        extra_args: "--index-url https://wheels.galaxyproject.org/simple/ --extra-index-url https://pypi.python.org/simple {{ pip_extra_args | default('') }}"
        virtualenv: "{{ galaxy_venv_dir }}"
        virtualenv_command: "{{ galaxy_virtualenv_command | default(pip_virtualenv_command | default(omit)) }}"
      environment:
        PYTHONPATH: null
        VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
      when: (not ansible_check_mode) and conditional_dependencies.stdout_lines | length > 0
```

If your job config file is written out prior to these tasks executing, it should have installed `drmaa`.

You can also add arbitrary packages to install in the list `galaxy_additional_venv_packages`.
