### ISSUE TITLE
Support for setting `GALAXY_INSTALL_PREBUILT_CLIENT`

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/ansible-galaxy#207]
Since we're not using `run.sh`, we'll need to re-implement it, but it would be really nice to have support for this variable. I don't think there's *many* (any?) other run.sh variables we really want to make configurable but this is definitely one.

**Comment by dometto** [comment]
Is this being worked on? If not, I would be happy to open a PR. The ability to support the prebuilt client is crucial for us as we are aiming to do cloud deployments of galaxy, and building is slowing down deployment unacceptably long. Optionally using the prebuilt client in ansible would be a great solution!

In fact, I've modified the `client.yml` tasks and already got this to work in its most basic form with:

```yaml
- name: Install prebuilt client via with yarn
  yarn:
    executable: "yarn --network-timeout 300000 --check-files"
    path: "{{ galaxy_server_dir }}"
  environment:
    PATH: "{{ galaxy_venv_dir }}/bin:{{ ansible_env.PATH }}"
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  when: not __galaxy_from_git.stat.exists or (__galaxy_client_build_version != __galaxy_current_commit_id)

- name: Stage prebuilt client
  command: "yarn run stage"
  args:
    chdir: "{{ galaxy_server_dir }}"
  environment:
    PATH: "{{ galaxy_server_dir }}/client/node_modules/.bin:{{ galaxy_venv_dir }}/bin:{{ ansible_env.PATH }}"
    VIRTUAL_ENV: "{{ galaxy_venv_dir }}"
  when: "__galaxy_major_version is version('23.0', '>=')"
```

I noticed that the `client_build_hash.txt` does not match the expect git commit value, so currently the role executes these steps every time I run my playbook, but I assume this would be fixed as soon as a new release of the prebuilt client is done?
