### ISSUE TITLE
When local tool is a folder

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/ansible-galaxy#214]
Hi ,
I have a locally developed tool, which I am trying to install in our local galaxy instance by setting `galaxy_local_tool` . This particular tool has a tool script, macro xml and test data. I would be grateful to know as how to add this to `galaxy_local_tools`. What worked was - 

```
galaxy_local_tools:
    - file: my_tool/
      section_name: SCS
      section_id: scs
    - file: my_tool/tool_name.xml
      section_name: SCS
      section_id: scs
```
The trailing slash seems to be necessary for correct copying of the folder.
