### ISSUE TITLE
Duplicate dictionary keys not allowed

### ISSUE THREAD

**Issue by ic4f** [galaxyproject/ansible-galaxy#42]
Accoring to this project's [README](https://github.com/galaxyproject/ansible-galaxy/blob/master/README.md) and [Galaxy documentation](https://docs.galaxyproject.org/en/master/admin/scaling.html#deployment-options), the following is part of a valid playbook configuration:
```yml
uwsgi:
  mule: lib/galaxy/main.py
  mule: lib/galaxy/main.py
```

However, this does not work: Ansible expects legal YAML, which does not allow duplicate dictionary keys. As a result, **only the last key will be processed**.

This would work if these were items in a sequence:
```yml
uwsgi:
  some-key:
    - mule: lib/galaxy/main.py
    - mule: lib/galaxy/main.py
```

However, that changes the format of the output configuration used by uwsgi.

One solution is to transform Ansible's output, flattening the sequence by "pulling it" up one level and removing its key. This can be done with a custom Ansible plugin. I'm submitting a pull request with a possible solution (this could be overkill if the uwsgi format can be easily changed to expect a sequence of mules, or other duplicate keys... )
