### ISSUE TITLE
uWSGI config loses order

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/ansible-galaxy#66]
Currently, we take the contents of `galaxy_config.uwsgi` (the value of which is a hash) to generate the `uwsgi:` section of `galaxy.yml`, and do some munging in the `uwsgi_yaml` filter plugin to turn it in to uWSGI's non-conforming internal yaml syntax.

In uWSGI config syntax the order of options matter, because it has control structures like:

```yaml
galaxy_config:
  uwsgi:
    if-exists: /srv/galaxy/test/var/zerg-run.fifo
    hook-accepting1-once: writefifo:/srv/galaxy/test/var/zerg-run.fifo 2q
    endif:
```

However, our template just sorts the keys of the hash and writes them in that order. You can work around this with e.g.:

```yaml
galaxy_config:
  uwsgi:
    if-exists: |
      {{ galaxy_mutable_data_dir }}/zerg-run.fifo
      hook-accepting1-once: writefifo:{{ galaxy_mutable_data_dir }}/zerg-run.fifo 2q
      endif:
```

If you need to have more than one `if-exists` block, you should be able to put the "body" of the block into list members underneath `galaxy_config.uwsgi.if-exists`. Even with this workaround, we still may write an invalid config because certain blocks or individual directives may need to come before others.

But we should probably allow `galaxy_config.uwsgi` to be a list so that the role user's order can be maintained. List member values could be either a hash with a single key/value:

```yaml
galaxy_config:
  uwsgi:
    - {socket: 127.0.0.1:4096}
    - {if-exists: {{ galaxy_mutable_data_dir }}/zerg-run.fifo}
    - {hook-accepting1-once: writefifo:{{ galaxy_mutable_data_dir }}/zerg-run.fifo 2q}
    - {endif: null}
```

or just a string in uWSGI-yaml syntax (same as above but members are not wrapped in `{ ... }`).

This raises a related question: if you compile uWSGI against libyaml, does that make it impossible to use these control structures, since then the config needs to be in proper yaml syntax?
