### ISSUE TITLE
Nginx proxy permission denied to static content

### ISSUE THREAD

**Issue by maikknebel** [galaxyproject/ansible-galaxy#69]
Hello,
i'm trying to set up an server with ansible and followed the galaxy [admin training tutorial](https://galaxyproject.github.io/training-material/topics/admin/tutorials/ansible-galaxy/tutorial.html#galaxy). Everything is working well so far. Now i tried to use some of the best practice settings, that are described in the readme of this repo. Problem is now, that the nginx doesn't have access to the static file folder.

All file are placed in /srv/galaxy and are only accessable by the galaxy-group. The static content that nginx should serve is placed in /srv/galaxy/server/static. When nginx tries to server the static files, i get a permission denied error, because nginx is not part of the galaxy group and is not allowed to read anything in /srv/galaxy/* and i dont want to give nginx full read access to my galaxy folder including configs etc.

My plan is so far, that i will have to write a role, that will copy the content of /srv/galaxy/server/static to /var/www/ and change permissions to www-data so nginx can access and serve them.

Is there any better solution for this? (Maybe a config-var that lets ansible deploy static content to a custom location)
Is using nginx as proxy to serve static a good way of should i just let uwsgi do the job?

Some of my group_vars
```
...
galaxy_separate_privileges: true
galaxy_manage_paths: true
galaxy_layout: root-dir
galaxy_root: /srv/galaxy
galaxy_file_path: /data
galaxy_user:
  name: galaxy
  shell: /bin/bash
galaxy_group: galaxy
galaxy_privsep_user: gxpriv
galaxy_commit_id: release_19.01
...
galaxy_config:
  galaxy:
    ...
    file_path: /data
    ...
  uwsgi:
    ...
    socket: 127.0.0.1:8080
    static-map:
      - /static/style={{ galaxy_server_dir }}/static/style/blue
      - /static={{ galaxy_server_dir }}/static
    master: true
    ...

nginx_package_name: nginx-full 
nginx_remove_default_vhost: true
nginx_server_names_hash_bucket_size: "128"
nginx_vhosts:
  - listen: 80
    server_name: "{{ hostname }}"
    root: "/var/www/{{ hostname }}"
    index: index.html
    access_log: /var/log/nginx/access.log
    error_log: /var/log/nginx/error.log
    state: present
    filename: "{{ hostname }}.conf"
    extra_parameters: |
        client_max_body_size 10G; 
        uwsgi_read_timeout 2400; 
        location / {
            uwsgi_pass      127.0.0.1:8080;
            uwsgi_param UWSGI_SCHEME $scheme;
            include         uwsgi_params;
        }
        location /static {
                alias {{ galaxy_server_dir }}/static;
                expires 24h;
        }
        ....
```

Parts of my playbook.yml
```
  roles:
    - galaxyproject.repos
    - role: galaxyproject.postgresql
      become: true
    - role: natefoo.postgresql_objects
      become: true
      become_user: postgres
    - galaxyproject.galaxy
    - role: geerlingguy.pip
      become: true
    - role: customModifications
      become: true
      become_user: gxpriv
    - role: usegalaxy-eu.supervisor
      become: true
    - role: geerlingguy.nginx
      become: true
```
