### ISSUE TITLE
Correct configuration to use slurm for jobs

### ISSUE THREAD

**Issue by maikknebel** [galaxyproject/ansible-galaxy#70]
Hello,

i am trying to run admin training for [Connecting Galaxy to a compute cluster](https://galaxyproject.github.io/training-material/topics/admin/tutorials/connect-to-compute-cluster/tutorial.html#galaxy-and-slurm). I could reproduce the steps until "Galaxy and Slurm". The first log output is different and i couldn't figure out why/what i have to do to make it look like expected.
How needs my uwsgi configuration has to look like to be able to run jobs on the slurm-nodes?
I tried to leave some of the config parts already, but nothing really worked.

Part of my config_vars (the config i use comes from ansible galaxy deployment admin training)
```
galaxy_config:
  ...
  uwsgi:
    # Default values
    socket: 127.0.0.1:8080
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map:
      - /static/style={{ galaxy_server_dir }}/static/style/blue
      - /static={{ galaxy_server_dir }}/static
    master: true
    virtualenv: "{{ galaxy_venv_dir }}"
    pythonpath: "{{ galaxy_server_dir }}/lib"
    module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
    thunder-lock: true
    die-on-term: true
    hook-master-start:
      - unix_signal:2 gracefully_kill_them_all
      - unix_signal:15 gracefully_kill_them_all
    py-call-osafterfork: true
    enable-threads: true
    # Our additions
    mule:
      - lib/galaxy/main.py
      - lib/galaxy/main.py
    farm: job-handlers:1,2
```

job_conf.xml
```
<?xml version="1.0"?>
<job_conf>
    <plugins workers="4">
        <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner"/>
        <plugin id="slurm" type="runner" load="galaxy.jobs.runners.slurm:SlurmJobRunner"/>
    </plugins>
    <destinations default="slurm">
        <destination id="slurm" runner="slurm"/>
        <destination id="local" runner="local"/>
    </destinations>
</job_conf>
```
